name: overscript
description: Overscript for running and building ctct stuff.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  flutter:
    sdk: flutter
  xterm: 2.5.0-pre
  pty: ^0.1.1
  # dcli: ^1.5.4
  path: ^1.8.0
  args: ^2.1.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  streaming_shared_preferences: ^2.0.0
  settings_ui: ^1.0.0
  get: ^4.1.4
  uuid: ^3.0.4
  ansicolor: ^2.0.1
  cool_alert: ^1.1.0
  checked_yaml: ^2.0.1
  interpolator: ^0.1.0
  mutex: ^3.0.0
  file_selector: ^0.8.2+1
  file_selector_linux: ^0.0.2+1
  # universal_platform: ^1.0.0+1
  window_manager: ^0.1.1
  dog: ^1.4.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: HEAD
  json_annotation: ^4.3.0      
  
dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.0
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  json_serializable: ^6.0.1
  

  # flutter pub run build_runner build

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
